name: Deploy MERN App 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/Tour-Travel-Booking-Web-App/routes/
          git reset --hard
          git pull origin main

      - name: Install dependencies
        run: |
          cd ~/Tour-Travel-Booking-Web-App/routes/
          sudo npm install

      - name: Restart PM2
        run: |
          pm2 restart backend || pm2 start index.js --name backend
          pm2 save

      - name: Install frontend dependencies
        run: |
          cd ~/Tour-Travel-Booking-Web-App/tour
          sudo npm install

      - name: Build Frontend
        run: |
          cd ~/Tour-Travel-Booking-Web-App/tour
          sudo npm run build

      - name: Deploy frontend build to Nginx folder
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r ~/Tour-Travel-Booking-Web-App/tour/build/* /var/www/html/

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
