name: Deploy MERN App 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/Tour-Travel-Booking-Web-App
          git reset --hard
          git pull origin main

      - name: Install backend dependencies
        run: |
          cd ~/Tour-Travel-Booking-Web-App/routes
          npm install

      - name: Restart PM2 Backend
        run: |
          pm2 restart backend || pm2 start ~/Tour-Travel-Booking-Web-App/routes/index.js --name backend
          pm2 save

      - name: Build & Deploy Frontend
        run: |
          cd ~/Tour-Travel-Booking-Web-App/tour
          npm install --legacy-peer-deps
          npm run build
          sudo rsync -a --delete build/ /var/www/html/
          sudo systemctl restart nginx
